# Summary Functions
these restructure the data in some useful way

## 1. describe()
This method generates a high-level summary of the attributes of the given column. It is type-aware, meaning that its output changes based on the data type of the input.
## 2. mean()
returns the mean 
## 3. unique()
returns the list of the unique values

# Maps()
A map is a term, borrowed from mathematics, for a function that takes one set of values and "maps" them to another set of values. In data science we often have a need for creating new representations from existing data, or for transforming data from the format it is in now to the format that we want it to be in later. Maps are what handle this work, making them extremely important for getting your work done!

There are two mapping methods that you will use often.

### 1. map()
is the first, and slightly simpler one. For example, suppose that we wanted to remean the scores the wines received to 0. We can do this as follows:

`review_points_mean = reviews.points.mean()
reviews.points.map(lambda p: p - review_points_mean)`
The function you pass to map() should expect a single value from the Series (a point value, in the above example), and return a transformed version of that value. map() returns a new Series where all the values have been transformed by your function.

### 2. apply()
 is the equivalent method if we want to transform a whole DataFrame by calling a custom method on each row.

`def remean_points(row):
    row.points = row.points - review_points_mean
    return row

reviews.apply(remean_points, axis='columns')
`
## note
Note that map() and apply() return new, transformed Series and DataFrames, respectively. They don't modify the original data they're called on.

In [1]:
import pandas as pd
df = pd.read_csv("datasets/titanic.csv")
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [2]:
df["Age"].mean() # average age

np.float64(29.69911764705882)

In [3]:
df["Age"].median() # middle age

np.float64(28.0)

In [4]:
df["Age"].min() # min age

np.float64(0.42)

In [5]:
df["Fare"].sum() # total fare

np.float64(28693.9493)

In [6]:
df["Fare"].count() # number of non-missing fare values

np.int64(891)

In [7]:
df["Age"].std() # how much values are spread out around the mean

np.float64(14.526497332334042)

In [8]:
df.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

In [9]:
df["Age"].describe()

count    714.000000
mean      29.699118
std       14.526497
min        0.420000
25%       20.125000
50%       28.000000
75%       38.000000
max       80.000000
Name: Age, dtype: float64

In [10]:
df["Sex"].unique()

<StringArray>
['male', 'female']
Length: 2, dtype: str

In [11]:
df["Pclass"].unique()

array([3, 1, 2])

In [12]:
df["Pclass"].nunique() # gives the number of unique values.

3

In [13]:
df["Sex"].value_counts()

Sex
male      577
female    314
Name: count, dtype: int64

In [14]:
df["Pclass"].value_counts()

Pclass
3    491
1    216
2    184
Name: count, dtype: int64

In [15]:
df["Sex"].value_counts(normalize=True) # instead of counts welll get proportions

Sex
male      0.647587
female    0.352413
Name: proportion, dtype: float64

# Maps()

In [16]:
# suppose we want to convert male -> 0 and female -> 1
df["Sex"].map({
    "male" : 0,
    "female" : 1
})

0      0
1      1
2      1
3      1
4      0
      ..
886    0
887    1
888    1
889    0
890    0
Name: Sex, Length: 891, dtype: int64

In [17]:
# map with a function
df["Fare"].map(lambda x: x * 2)

0       14.5000
1      142.5666
2       15.8500
3      106.2000
4       16.1000
         ...
886     26.0000
887     60.0000
888     46.9000
889     60.0000
890     15.5000
Name: Fare, Length: 891, dtype: float64

# Apply()

In [18]:
# it is more general
df["Fare"].apply(lambda x:x * 2)

0       14.5000
1      142.5666
2       15.8500
3      106.2000
4       16.1000
         ...
886     26.0000
887     60.0000
888     46.9000
889     60.0000
890     15.5000
Name: Fare, Length: 891, dtype: float64

In [19]:
# apply can operate across dataframe rows/column
df[["Age", "Fare"]].apply(lambda x: x.mean())

Age     29.699118
Fare    32.204208
dtype: float64

In [20]:
# summary functions + filtering
df.loc[df["Sex"] == "female", "Age"].mean()

np.float64(27.915708812260537)

In [21]:
# average fare for the 1st class passenger
df.loc[df["Pclass"] == 1, "Fare"].mean()

np.float64(84.1546875)

In [22]:
# average age of survivors
df.loc[df["Survived"] == 1, "Age"].mean()

np.float64(28.343689655172415)

In [24]:
# majority survivors gender
df.loc[df["Survived"] == 1, "Sex"].value_counts()

Sex
female    233
male      109
Name: count, dtype: int64

# MULTI CONDITIONS + SUMMARY

In [25]:
# avg fare for female 1st-class passengers
df.loc[
    (df["Sex"] == "female") &
    (df["Pclass"] == 1),
    "Fare"
].mean()

np.float64(106.12579787234043)

## axis
by default pandas calculates down the columns

In [26]:
df[["Age", "Fare"]].mean(axis=1) # now it calclates row wise mean for the age and fare

0      14.62500
1      54.64165
2      16.96250
3      44.05000
4      21.52500
         ...
886    20.00000
887    24.50000
888    23.45000
889    28.00000
890    19.87500
Length: 891, dtype: float64

# idxmax() / idxmin()
Useful when you don't just want the maximum value but the index where it occurs.

In [27]:
# index of the passenger with the hightest fare
df["Fare"].idxmax()

258

In [28]:
# checking the above passenger was died or not
df.loc[df["Fare"].idxmax(), "Survived"]

np.int64(1)

# cheat sheet
# Summary

df["Age"].mean()

df["Age"].median()

df["Age"].min()

df["Age"].max()

df["Age"].sum()

df["Age"].std()

df["Age"].count()

# Statistics overview

df.describe()


# Unique values

df["Sex"].unique()

df["Sex"].nunique()

# Frequency

df["Sex"].value_counts()

df["Sex"].value_counts(normalize=True)

# Mapping

df["Sex"].map({
    "male": 0,
    "female": 1
})


# General transformation

df["Fare"].apply(lambda x: x * 2)

# Index of extreme values

df["Fare"].idxmax()

df["Fare"].idxmin()


# Conditional summary

df.loc[df["Sex"] == "female", "Age"].mean()

In [33]:
df["sex_encoded"]= df["Sex"].map({
    "male" : 0,
    "female" : 1
})
df["sex_encoded"].head()

0    0
1    1
2    1
3    1
4    0
Name: sex_encoded, dtype: int64